local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   rolling_window: true
   width: 4.0
   height: 4.0
   resolution: 0.1
   transform_tolerance: 0.5

   plugins:
    - {name: laser_layer,         type: "costmap_2d::ObstacleLayer"} 

    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
